# This is a boilerplate parameters config generated for pipeline 'data_modeling'
# using Kedro 1.0.0.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/1.0.0/configuration/parameters.html

XGBClassifier:
  random_state: 42
  eval_metric: "mlogloss"
  use_label_encoder: False
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 5
  min_samples_split: 10
  min_samples_leaf: 5
  subsample: 0.8
  colsample_bytree: 0.8
